### PR TITLE
feat: update rollup to 3.26.0

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@Swatinem Do you have any idea about why ci fail?

**Comment by Swatinem** [comment]
Yes, I believe you can bless the test snapshots, looks like its just changes to how rollup does code splitting.

**Comment by xiaoxiangmoe** [comment]
@Swatinem Please review it.

* I run `prettier --write ./tests` to format code.
* Add `rollupVersion` field in testcases's `Meta`
* fix bug for meta.tsVersion compare
* update rollup to 3.26.0

**Review by Swatinem — APPROVED** [review]

**Comment by privatenumber** [comment]
Rollup v2.79.1 doesn't support `onLog`. Seems like this should've been released as a breaking change?

**Pull request merged**
