### PR TITLE
fix: create program for `imports` input file #318

### PR DESCRIPTION
**Pull request by NWYLZW**

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
would be nice to have a testcase for this as well

**Comment by NWYLZW** [comment]
> would be nice to have a testcase for this as well

I also want to write a test case. However, it seems that currently the fixture does not support declare `impoets` by package. After failing to write a unit test, I gave up. Do you have any good ideas or suggestions?

**Comment by brc-dd** [comment]
For some reason this commit is doubling the memory usage.

On https://github.com/vuejs/vitepress (`pnpm build`):

With 989ec06:

```
       16.99 real        19.25 user         2.32 sys
          1190477824  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
              228341  page reclaims
                  73  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                 103  messages sent
                 109  messages received
                 315  signals received
                1105  voluntary context switches
              103013  involuntary context switches
          1819354192  instructions retired
           666763407  cycles elapsed
            75255232  peak memory footprint
```

With e74fb86:

```
       16.99 real        19.25 user         2.32 sys
          1190477824  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
              228341  page reclaims
                  73  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                 103  messages sent
                 109  messages received
                 315  signals received
                1105  voluntary context switches
              103013  involuntary context switches
          1819354192  instructions retired
           666763407  cycles elapsed
            75255232  peak memory footprint
```

**Comment by NWYLZW** [comment]
This is a helpless thing. TypeScript doesn't provide any other way to support the emit mode of multiple Programs. This is a sacrifice that has to be made for "correctness".

**Pull request merged**
