### PR TITLE
test: ambient const/function

### PR DESCRIPTION
**Pull request by aleclarson**
Related: #24

This does *not* include a fix. 😢

### CODE REVIEW

**Comment by aleclarson** [comment]
I've also made it so the `intl-codegen` test is skipped by default, since it requires a symlink to pass.

**Comment by Swatinem** [comment]
@aleclarson thanks for the report and the testcases. :-)

So far I haven’t very much tested consuming *handwritten* `.d.ts` files.
The `.d.ts` files generated by `tsc` should all have `declare` modifiers on them, except for `export default`, which I work around in a quite ugly way

https://github.com/Swatinem/rollup-plugin-dts/blob/191e42805662e66be867968285d21d8ead95d017/src/compiler.ts#L178-L182

So my question is, are you sure that the `.d.ts` files are actually valid? Running `tsc` on them with `skipLibCheck: false` yields the following error at least:

```
error TS1183: An implementation cannot be declared in ambient contexts.

6 export function foo() {}
                        ~
```

**Comment by aleclarson** [comment]
Fixed the `ambient-function` test case!



> So far I haven’t very much tested consuming _handwritten_ `.d.ts` files.

Ah that's too bad. The `.d.ts` modules I have are definitely correct. Looks like we need to replace the `export` with a `declare` instead of merely stripping the `export` keyword.

**Comment by Swatinem** [comment]
I think this is a bit related to the way I use the typescript compiler.

I basically do an ahead-of-time compile, because it is the easiest to implement. However it causes a few problems, one of them is performance, and also #15.

I think I can solve those, and also this problem when I switch over to using a different compiler mode of typescript, which hopefully lets me do all of this stuff…

However its quite complex to implement -_- as all these APIs are not quite that well documented.

How urgent is this for you? And are these files indeed *hardwritten*? In which case you can either just add the `declare`, or if its an external `@types`, just add it to `external` to not process it at all.

**Comment by aleclarson** [comment]
No hurry. I can just skip bundling altogether for now. Thanks!

**Comment by aleclarson** [comment]
I decided to stop using `.d.ts` modules in most of `react-spring` and then add an explicit `declare` in the few remaining `.d.ts` modules, and this has worked nicely.

Another thing to note: This package seems to prepend the `declare` keyword to every `type` declaration, and that's not necessary (though, it doesn't hurt either).

**Comment by Swatinem** [comment]
> This package seems to prepend the `declare` keyword to every `type` declaration

Well thats typescripts own doing :-)

**Comment by Swatinem** [comment]
going to close this as per https://github.com/Swatinem/rollup-plugin-dts/issues/24#issuecomment-498238530

**Pull request closed without merging**
